"""initial_schema

Revision ID: c5bd66b5f125
Revises: 
Create Date: 2026-03-28 23:42:41.372437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5bd66b5f125'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iam_users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_iam_users')),
    sa.UniqueConstraint('username', 'is_deleted', name='uk_iam_users_username')
    )
    op.create_table('core_workspaces',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('workspace_code', sa.String(length=64), nullable=False),
    sa.Column('workspace_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['iam_users.id'], name=op.f('fk_core_workspaces_owner_user_id_iam_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_workspaces')),
    sa.UniqueConstraint('workspace_code', 'is_deleted', name='uk_core_workspaces_code')
    )
    op.create_table('iam_sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('session_code', sa.String(length=64), nullable=False),
    sa.Column('access_token_jti', sa.String(length=64), nullable=False),
    sa.Column('client_type', sa.String(length=32), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['iam_users.id'], name=op.f('fk_iam_sessions_user_id_iam_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_iam_sessions')),
    sa.UniqueConstraint('access_token_jti', name=op.f('uq_iam_sessions_access_token_jti')),
    sa.UniqueConstraint('session_code', name=op.f('uq_iam_sessions_session_code'))
    )
    op.create_table('asset_media_objects',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('storage_type', sa.String(length=32), nullable=False),
    sa.Column('bucket_name', sa.String(length=128), nullable=True),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('usage', sa.String(length=32), nullable=False),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['core_workspaces.id'], name=op.f('fk_asset_media_objects_workspace_id_core_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_media_objects')),
    sa.UniqueConstraint('checksum_sha256', 'file_size', 'workspace_id', name='uk_asset_media_objects_checksum')
    )
    op.create_table('asset_templates',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('template_code', sa.String(length=64), nullable=False),
    sa.Column('template_name', sa.String(length=128), nullable=False),
    sa.Column('template_type', sa.String(length=32), nullable=False),
    sa.Column('match_strategy', sa.String(length=32), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_baseline_revision_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['core_workspaces.id'], name=op.f('fk_asset_templates_workspace_id_core_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_templates')),
    sa.UniqueConstraint('workspace_id', 'template_code', 'is_deleted', name='uk_asset_templates')
    )
    op.create_table('case_components',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('component_code', sa.String(length=64), nullable=False),
    sa.Column('component_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['core_workspaces.id'], name=op.f('fk_case_components_workspace_id_core_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_components')),
    sa.UniqueConstraint('workspace_id', 'component_code', 'is_deleted', name='uk_case_components')
    )
    op.create_table('case_test_cases',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('case_code', sa.String(length=64), nullable=False),
    sa.Column('case_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['core_workspaces.id'], name=op.f('fk_case_test_cases_workspace_id_core_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_test_cases')),
    sa.UniqueConstraint('workspace_id', 'case_code', 'is_deleted', name='uk_case_test_cases')
    )
    op.create_table('case_test_suites',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('suite_code', sa.String(length=64), nullable=False),
    sa.Column('suite_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['core_workspaces.id'], name=op.f('fk_case_test_suites_workspace_id_core_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_test_suites')),
    sa.UniqueConstraint('workspace_id', 'suite_code', 'is_deleted', name='uk_case_test_suites')
    )
    op.create_table('cfg_device_profiles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('viewport_width', sa.Integer(), nullable=False),
    sa.Column('viewport_height', sa.Integer(), nullable=False),
    sa.Column('device_scale_factor', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['core_workspaces.id'], name=op.f('fk_cfg_device_profiles_workspace_id_core_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfg_device_profiles')),
    sa.UniqueConstraint('workspace_id', 'profile_name', 'is_deleted', name='uk_cfg_device_profiles')
    )
    op.create_table('cfg_environment_profiles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['core_workspaces.id'], name=op.f('fk_cfg_environment_profiles_workspace_id_core_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfg_environment_profiles')),
    sa.UniqueConstraint('workspace_id', 'profile_name', 'is_deleted', name='uk_cfg_environment_profiles')
    )
    op.create_table('core_workspace_members',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('workspace_role', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['iam_users.id'], name=op.f('fk_core_workspace_members_user_id_iam_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['core_workspaces.id'], name=op.f('fk_core_workspace_members_workspace_id_core_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uk_core_workspace_members')
    )
    op.create_table('iam_refresh_tokens',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['iam_sessions.id'], name=op.f('fk_iam_refresh_tokens_session_id_iam_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_iam_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_iam_refresh_tokens_token_hash'))
    )
    op.create_table('asset_baseline_revisions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('template_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('media_object_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_object_id'], ['asset_media_objects.id'], name=op.f('fk_asset_baseline_revisions_media_object_id_asset_media_objects')),
    sa.ForeignKeyConstraint(['template_id'], ['asset_templates.id'], name=op.f('fk_asset_baseline_revisions_template_id_asset_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_baseline_revisions')),
    sa.UniqueConstraint('template_id', 'revision_no', name='uk_asset_baseline_revisions')
    )
    op.create_table('asset_template_mask_regions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('template_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('region_name', sa.String(length=128), nullable=False),
    sa.Column('x_ratio', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('y_ratio', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('width_ratio', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('height_ratio', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['asset_templates.id'], name=op.f('fk_asset_template_mask_regions_template_id_asset_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_template_mask_regions'))
    )
    op.create_table('case_component_steps',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('component_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=32), nullable=False),
    sa.Column('step_name', sa.String(length=128), nullable=False),
    sa.Column('template_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['case_components.id'], name=op.f('fk_case_component_steps_component_id_case_components')),
    sa.ForeignKeyConstraint(['template_id'], ['asset_templates.id'], name=op.f('fk_case_component_steps_template_id_asset_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_component_steps')),
    sa.UniqueConstraint('component_id', 'step_no', name='uk_case_component_steps')
    )
    op.create_table('case_suite_cases',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('test_suite_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('test_case_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['case_test_cases.id'], name=op.f('fk_case_suite_cases_test_case_id_case_test_cases')),
    sa.ForeignKeyConstraint(['test_suite_id'], ['case_test_suites.id'], name=op.f('fk_case_suite_cases_test_suite_id_case_test_suites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_suite_cases')),
    sa.UniqueConstraint('test_suite_id', 'sort_order', name='uk_case_suite_sort'),
    sa.UniqueConstraint('test_suite_id', 'test_case_id', name='uk_case_suite_cases')
    )
    op.create_table('case_test_case_steps',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('test_case_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=32), nullable=False),
    sa.Column('step_name', sa.String(length=128), nullable=False),
    sa.Column('component_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('template_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('retry_times', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['case_components.id'], name=op.f('fk_case_test_case_steps_component_id_case_components')),
    sa.ForeignKeyConstraint(['template_id'], ['asset_templates.id'], name=op.f('fk_case_test_case_steps_template_id_asset_templates')),
    sa.ForeignKeyConstraint(['test_case_id'], ['case_test_cases.id'], name=op.f('fk_case_test_case_steps_test_case_id_case_test_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_test_case_steps')),
    sa.UniqueConstraint('test_case_id', 'step_no', name='uk_case_test_case_steps')
    )
    op.create_table('cfg_environment_variables',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('environment_profile_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('var_key', sa.String(length=128), nullable=False),
    sa.Column('var_value_ciphertext', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_profile_id'], ['cfg_environment_profiles.id'], name=op.f('fk_cfg_environment_variables_environment_profile_id_cfg_environment_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfg_environment_variables')),
    sa.UniqueConstraint('environment_profile_id', 'var_key', name='uk_cfg_environment_variables')
    )
    op.create_table('exec_test_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('test_suite_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('environment_profile_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('device_profile_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('trigger_source', sa.String(length=32), nullable=False),
    sa.Column('triggered_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_case_count', sa.Integer(), nullable=False),
    sa.Column('passed_case_count', sa.Integer(), nullable=False),
    sa.Column('failed_case_count', sa.Integer(), nullable=False),
    sa.Column('error_case_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_profile_id'], ['cfg_device_profiles.id'], name=op.f('fk_exec_test_runs_device_profile_id_cfg_device_profiles')),
    sa.ForeignKeyConstraint(['environment_profile_id'], ['cfg_environment_profiles.id'], name=op.f('fk_exec_test_runs_environment_profile_id_cfg_environment_profiles')),
    sa.ForeignKeyConstraint(['test_suite_id'], ['case_test_suites.id'], name=op.f('fk_exec_test_runs_test_suite_id_case_test_suites')),
    sa.ForeignKeyConstraint(['triggered_by'], ['iam_users.id'], name=op.f('fk_exec_test_runs_triggered_by_iam_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['core_workspaces.id'], name=op.f('fk_exec_test_runs_workspace_id_core_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exec_test_runs')),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name='uk_exec_test_runs_idempotency')
    )
    op.create_table('exec_test_case_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('test_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('test_case_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('failure_reason_code', sa.String(length=64), nullable=True),
    sa.Column('failure_summary', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['case_test_cases.id'], name=op.f('fk_exec_test_case_runs_test_case_id_case_test_cases')),
    sa.ForeignKeyConstraint(['test_run_id'], ['exec_test_runs.id'], name=op.f('fk_exec_test_case_runs_test_run_id_exec_test_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exec_test_case_runs'))
    )
    op.create_table('report_run_reports',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('test_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('summary_status', sa.String(length=32), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['exec_test_runs.id'], name=op.f('fk_report_run_reports_test_run_id_exec_test_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_run_reports')),
    sa.UniqueConstraint('test_run_id', name=op.f('uq_report_run_reports_test_run_id'))
    )
    op.create_table('exec_step_results',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('case_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('score_value', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('expected_media_object_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('actual_media_object_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('diff_media_object_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actual_media_object_id'], ['asset_media_objects.id'], name=op.f('fk_exec_step_results_actual_media_object_id_asset_media_objects')),
    sa.ForeignKeyConstraint(['case_run_id'], ['exec_test_case_runs.id'], name=op.f('fk_exec_step_results_case_run_id_exec_test_case_runs')),
    sa.ForeignKeyConstraint(['diff_media_object_id'], ['asset_media_objects.id'], name=op.f('fk_exec_step_results_diff_media_object_id_asset_media_objects')),
    sa.ForeignKeyConstraint(['expected_media_object_id'], ['asset_media_objects.id'], name=op.f('fk_exec_step_results_expected_media_object_id_asset_media_objects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exec_step_results')),
    sa.UniqueConstraint('case_run_id', 'step_no', name='uk_exec_step_results')
    )
    op.create_table('report_artifacts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('media_object_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('artifact_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_object_id'], ['asset_media_objects.id'], name=op.f('fk_report_artifacts_media_object_id_asset_media_objects')),
    sa.ForeignKeyConstraint(['report_id'], ['report_run_reports.id'], name=op.f('fk_report_artifacts_report_id_report_run_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_artifacts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_artifacts')
    op.drop_table('exec_step_results')
    op.drop_table('report_run_reports')
    op.drop_table('exec_test_case_runs')
    op.drop_table('exec_test_runs')
    op.drop_table('cfg_environment_variables')
    op.drop_table('case_test_case_steps')
    op.drop_table('case_suite_cases')
    op.drop_table('case_component_steps')
    op.drop_table('asset_template_mask_regions')
    op.drop_table('asset_baseline_revisions')
    op.drop_table('iam_refresh_tokens')
    op.drop_table('core_workspace_members')
    op.drop_table('cfg_environment_profiles')
    op.drop_table('cfg_device_profiles')
    op.drop_table('case_test_suites')
    op.drop_table('case_test_cases')
    op.drop_table('case_components')
    op.drop_table('asset_templates')
    op.drop_table('asset_media_objects')
    op.drop_table('iam_sessions')
    op.drop_table('core_workspaces')
    op.drop_table('iam_users')
    # ### end Alembic commands ###
